
//try catch finally throw throws

public class ExceptionDemo {

	public static void main(String[] args) {

		
		System.out.println("line 1");

		int[] x= {2,0};
		
		
		try {
			
			try {
			//System.out.println(10/x[1]);
				System.out.println(10/x[3]);
			}
			catch (ArithmeticException e) {
				System.out.println("nested "+e+" "+e.getMessage());
			}
		System.out.println(10/x[0]);
		System.out.println("hello");
		}
		catch (ArithmeticException e) {
		
			System.out.println("outer "+e+" "+e.getMessage());
		}
		catch (ArrayIndexOutOfBoundsException e) {
			
			System.out.println("outer "+e+" "+e.getMessage());
		}
		
		
		System.out.println("line 3");
		
		
	}

}



